/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazgrafica;

import conexion.ConexionBaseDatos;
import herencias.Idiomas;
import interfacespropias.Sonidos;
import java.applet.AudioClip;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author ShibaXpath
 */
public final class EmergenciasOperativas extends Idiomas implements Sonidos {

    private String nombreUsuario;
    private final ConexionBaseDatos cn;
    private String idiomaElegido = "";

    /**
     * Creates new form InicioApp
     */
    public EmergenciasOperativas() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Kizuna App");
        setResizable(false);
        setIconImage(getIconImage());
        nombreUsuario = "";
        cn = new ConexionBaseDatos();
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    public void setDatos(String dato) {
        datos.setText(dato);
    }

    public void setIdiomaElegido(String idiomaElegido) {
        this.idiomaElegido = idiomaElegido;
    }

    @Override
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/miicono.jpg"));

        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        union = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        separador4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        separador1 = new javax.swing.JSeparator();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTextArea();
        filtro = new javax.swing.JComboBox<>();
        actualizar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        separador3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        menuSesion = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        salida = new javax.swing.JMenuItem();
        idiomas = new javax.swing.JMenu();
        español = new javax.swing.JMenuItem();
        japones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1120, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(204, 204, 204));
        fondo.setPreferredSize(new java.awt.Dimension(580, 500));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        union.setBackground(new java.awt.Color(255, 0, 51));
        union.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        union.setForeground(new java.awt.Color(255, 255, 255));
        union.setText("UNIRSE");
        union.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unionActionPerformed(evt);
            }
        });
        fondo.add(union, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 150, 60));

        volver.setBackground(new java.awt.Color(255, 0, 51));
        volver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        fondo.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 140, 60));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        fondo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 10, 100));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        fondo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 10, 60));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        fondo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 10, 60));
        fondo.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 520, 20));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 10, 230));
        fondo.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 520, 10));
        fondo.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 520, 20));

        titulo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Titulo");
        fondo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        datos.setEditable(false);
        datos.setBackground(new java.awt.Color(204, 204, 204));
        datos.setColumns(20);
        datos.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        datos.setForeground(new java.awt.Color(0, 0, 0));
        datos.setRows(5);
        datos.setText(null);
        datos.setFocusable(false);
        datos.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(datos);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 510, 220));

        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español","日本語" }));
        fondo.add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, -1));

        actualizar.setBackground(new java.awt.Color(255, 0, 51));
        actualizar.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setText("Actualizar Lista");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        fondo.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        fondo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 10, 100));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        fondo.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 10, 100));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        fondo.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 10, 330));
        fondo.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 350, 20));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 580, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 500));

        archivo.setText("Archivo");

        salida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        salida.setText("Salir");
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        archivo.add(salida);

        menuSesion.add(archivo);

        idiomas.setText("Idiomas");

        español.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        español.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/espaicon.png"))); // NOI18N
        español.setText("Español");
        español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                españolActionPerformed(evt);
            }
        });
        idiomas.add(español);

        japones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_DOWN_MASK));
        japones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/japoicon.png"))); // NOI18N
        japones.setText("日本語");
        japones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japonesActionPerformed(evt);
            }
        });
        idiomas.add(japones);

        menuSesion.add(idiomas);

        setJMenuBar(menuSesion);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void japonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japonesActionPerformed
        cambiarIdioma(false);
        super.setBandera(false);
        idiomaElegido = "JP";
        setDatos(cn.devolverUltimoCaso(idiomaElegido));
    }//GEN-LAST:event_japonesActionPerformed

    private void españolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_españolActionPerformed
        cambiarIdioma(true);
        super.setBandera(true);
        idiomaElegido = "ESP";
        setDatos(cn.devolverUltimoCaso(idiomaElegido));
    }//GEN-LAST:event_españolActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Plataforma plata = new Plataforma();
        reproducirSonidoBoton();
        plata.setBandera(super.isBandera());
        plata.cambiarIdioma(super.isBandera());
        plata.setNombreUsuario(nombreUsuario);
        this.dispose();
        plata.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salidaActionPerformed

    private void unionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unionActionPerformed
        reproducirSonidoBoton(); // Reproduce un sonido relacionado con el botón presionado

        if (cn.devolverCasoUsuario(nombreUsuario))
        {
            // Si el método "devolverCasoUsuario" devuelve verdadero para el nombre de usuario
            if (super.isBandera())
            {
                JOptionPane.showMessageDialog(null, "Ya estás en un caso asignado.", "Mensaje de error", JOptionPane.WARNING_MESSAGE);
            } else
            {
                JOptionPane.showMessageDialog(null, "既に割り当てられたケースです。", "エラーメッセージ", JOptionPane.WARNING_MESSAGE);
            }
        } else if (cn.devolverCantidadCasos(idiomaElegido) == 0) //Si la cantidad de casos en ese idioma es 0.
        {
            if (super.isBandera())
            {
                JOptionPane.showMessageDialog(null, "No existe ningún caso para poder unirse.", "Mensaje de error", JOptionPane.WARNING_MESSAGE);
            } else
            {
                JOptionPane.showMessageDialog(null, "参加するためのケースが存在しません。", "エラーメッセージ", JOptionPane.WARNING_MESSAGE);
            }
        } else
        {
            // Si el usuario no tiene un caso asignado
            cn.modificarCasoUsuario(cn.devolverID_Caso(cn.devolverNombreCaso(cn.devolveIDCaso(idiomaElegido))), nombreUsuario);
            cn.modificarCaso(cn.devolverID_Usuario(nombreUsuario), cn.devolverNombreCaso(cn.devolveIDCaso(idiomaElegido)));
            cn.modificarCasoEnCurso(cn.devolverNombreCaso(cn.devolveIDCaso(idiomaElegido)), idiomaElegido);

            if (idiomaElegido.equals("ESP"))
            {
                JOptionPane.showMessageDialog(null, "Usted se ha unido al caso con éxito: " + nombreUsuario, "Mensaje informativo", JOptionPane.INFORMATION_MESSAGE);
            } else
            {
                JOptionPane.showMessageDialog(null, "ユーザー名" + nombreUsuario + "様、おめでとうございます。ケースに正常に参加しました。", "情報メッセージ", JOptionPane.INFORMATION_MESSAGE);
            }

            Plataforma plata = new Plataforma(); // Crea una instancia de la clase Plataforma
            reproducirSonidoBoton(); // Reproduce un sonido relacionado con el botón presionado
            plata.setBandera(super.isBandera());
            plata.cambiarIdioma(super.isBandera());
            plata.setNombreUsuario(nombreUsuario);
            this.dispose();
            plata.setVisible(true);
        }

    }//GEN-LAST:event_unionActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        reproducirSonidoBoton();
        if (filtro.getSelectedItem().toString().equals("Español") || filtro.getSelectedItem().toString().equals("スペイン語"))
        {
            idiomaElegido = "ESP";
        } else
        {
            idiomaElegido = "JP";
        }
        setDatos(cn.devolverUltimoCaso(idiomaElegido));
    }//GEN-LAST:event_actualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JMenu archivo;
    private javax.swing.JTextArea datos;
    private javax.swing.JMenuItem español;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JPanel fondo;
    private javax.swing.JMenu idiomas;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JMenuItem japones;
    private javax.swing.JMenuBar menuSesion;
    private javax.swing.JMenuItem salida;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton union;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cambiarIdioma(boolean idioma) {

        if (idioma)
        {
            filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]
            {
                "Español", "Japonés"
            }));
            archivo.setText("Archivo");
            idiomas.setText("Idiomas");
            salida.setText("Desconectar");
            volver.setFont(new java.awt.Font("Roboto", 0, 18));
            volver.setText("VOLVER");
            titulo.setText("ÚLTIMA EMERGENCIA DISPONIBLE PARA USTED:");
            titulo.setFont(new java.awt.Font("Roboto", 0, 24));
            union.setText("UNIRSE");
            union.setFont(new java.awt.Font("Roboto", 0, 18));
            actualizar.setText("Actualizar lista");
            imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondooperativas.jpg")));
        } else
        {
            filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]
            {
                "スペイン語", "日本語"
            }));
            imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondooperativasJP.jpg")));
            archivo.setText("アーカイブ");
            idiomas.setText("語");
            salida.setText("ディスコネクト");
            titulo.setText("あなたに利用可能な最新の緊急事態:");
            volver.setFont(new java.awt.Font("Dialog", 0, 18));
            titulo.setFont(new java.awt.Font("Dialog", 0, 24));
            volver.setText("戻る");
            union.setFont(new java.awt.Font("Dialog", 0, 18));
            union.setText("参加する");
            actualizar.setText("リストを更新する");
        }
    }

    @Override
    public AudioClip obtenerSonido() {
        AudioClip sonidoBoton;
        URL url = getClass().getResource("/sonidos/raton.wav");
        sonidoBoton = java.applet.Applet.newAudioClip(url);
        return sonidoBoton;
    }

    @Override
    public void reproducirSonidoBoton() {
        obtenerSonido().play();
    }
}
