/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazgrafica;

import conexion.ConexionBaseDatos;
import herencias.Idiomas;
import interfacespropias.Sonidos;
import java.applet.AudioClip;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author ShibaXpath
 */
public final class IniciarSesionApp extends Idiomas implements Sonidos {

    /**
     * Creates new form InicioApp
     */
    public IniciarSesionApp() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Kizuna App");
        setResizable(false);
        setIconImage(getIconImage());
        ingresar.setMnemonic(KeyEvent.VK_ENTER);
    }

    @Override
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/miicono.jpg"));

        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        usuario = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        contra = new javax.swing.JLabel();
        campoContra = new javax.swing.JPasswordField();
        volver = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        menuSesion = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        salida = new javax.swing.JMenuItem();
        idiomas = new javax.swing.JMenu();
        español = new javax.swing.JMenuItem();
        japones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(940, 645));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(204, 204, 204));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 0));
        usuario.setText("USUARIO:");
        fondo.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        campoUsuario.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });
        fondo.add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 150, 30));

        contra.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        contra.setForeground(new java.awt.Color(0, 0, 0));
        contra.setText("CONTRASEÑA:");
        fondo.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        campoContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContraActionPerformed(evt);
            }
        });
        fondo.add(campoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 150, 30));

        volver.setBackground(new java.awt.Color(255, 0, 51));
        volver.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        fondo.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 140, 60));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.jpg"))); // NOI18N
        fondo.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 250, -1));

        ingresar.setBackground(new java.awt.Color(255, 0, 51));
        ingresar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ingresar.setForeground(new java.awt.Color(255, 255, 255));
        ingresar.setText("INGRESAR");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        fondo.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 140, 60));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        fondo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 620));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 510, 630));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoSesion.jpg"))); // NOI18N
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 630));

        archivo.setText("Archivo");

        salida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        salida.setText("Salir");
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        archivo.add(salida);

        menuSesion.add(archivo);

        idiomas.setText("Idiomas");

        español.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        español.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/espaicon.png"))); // NOI18N
        español.setText("Español");
        español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                españolActionPerformed(evt);
            }
        });
        idiomas.add(español);

        japones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_DOWN_MASK));
        japones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/japoicon.png"))); // NOI18N
        japones.setText("日本語");
        japones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japonesActionPerformed(evt);
            }
        });
        idiomas.add(japones);

        menuSesion.add(idiomas);

        setJMenuBar(menuSesion);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void japonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japonesActionPerformed
        cambiarIdioma(false);
        super.setBandera(false);
    }//GEN-LAST:event_japonesActionPerformed

    private void españolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_españolActionPerformed
        cambiarIdioma(true);
        super.setBandera(true);
    }//GEN-LAST:event_españolActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        InicioApp inicio = new InicioApp();
        reproducirSonidoBoton();
        inicio.cambiarIdioma(super.isBandera());
        this.dispose();
        inicio.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salidaActionPerformed

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        reproducirSonidoBoton();
        ConexionBaseDatos cn = new ConexionBaseDatos();
        String pais = "";
        if (super.isBandera())
        {
            pais = "ESP";
        } else
        {
            pais = "JP";
        }
        Plataforma plata = new Plataforma();
        plata.setBandera(super.isBandera());
        plata.cambiarIdioma(super.isBandera());
        switch (pais)
        {
            case "ESP":
                //Comprueba condiciones no válidas y devuelve posibles errores, sino introduce a la plataforma.
                if (cn.comprobarUsuario(campoUsuario.getText()))
                {
                    if (cn.comprobarPass(campoUsuario.getText(), cn.encryptPassword(campoContra.getText())))
                    {
                        JOptionPane.showMessageDialog(null, "Iniciando sesión con el usuario: " + campoUsuario.getText(), "Mensaje de bienvenida", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                        plata.setNombreUsuario(campoUsuario.getText());
                        plata.setVisible(true);
                    } else
                    {
                        JOptionPane.showMessageDialog(null, "La contraseña no coincide con el usuario ingresado.", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
                    }
                } else
                {
                    JOptionPane.showMessageDialog(null, "No existe ningún usuario con ese nombre.", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
                }
                break;
            case "JP":
                //Comprueba condiciones no válidas y devuelve posibles errores, sino introduce a la plataforma.
                if (cn.comprobarUsuario(campoUsuario.getText()))
                {
                    if (cn.comprobarPass(campoUsuario.getText(), cn.encryptPassword(campoContra.getText())))
                    {
                        JOptionPane.showMessageDialog(null, "ユーザー：" + campoUsuario.getText() + "でログインする", "ウェルカムメッセージ", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                        plata.setNombreUsuario(campoUsuario.getText());
                        plata.setVisible(true);
                    } else
                    {
                        JOptionPane.showMessageDialog(null, "パスワードが入力されたユーザーと一致しない。", "エラーメッセージ", JOptionPane.ERROR_MESSAGE);
                    }
                } else
                {
                    JOptionPane.showMessageDialog(null, "この名前のユーザーは存在しません。", "エラーメッセージ", JOptionPane.ERROR_MESSAGE);
                }
                break;
        }
    }//GEN-LAST:event_ingresarActionPerformed

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        ingresar.doClick();
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void campoContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraActionPerformed
        ingresar.doClick();
    }//GEN-LAST:event_campoContraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivo;
    private javax.swing.JPasswordField campoContra;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel contra;
    private javax.swing.JMenuItem español;
    private javax.swing.JPanel fondo;
    private javax.swing.JMenu idiomas;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton ingresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JMenuItem japones;
    private javax.swing.JLabel logo;
    private javax.swing.JMenuBar menuSesion;
    private javax.swing.JMenuItem salida;
    private javax.swing.JLabel usuario;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cambiarIdioma(boolean idioma) {
        // Cambiar el idioma de la interfaz
        if (idioma)
        {
            // Configuraciones para el idioma español
            ingresar.setText("INGRESAR");
            ingresar.setFont(new java.awt.Font("Roboto", 0, 18));
            archivo.setText("Archivo");
            idiomas.setText("Idiomas");
            salida.setText("Desconectar");
            usuario.setText("USUARIO:");
            contra.setText("CONTRASEÑA:");
            volver.setFont(new java.awt.Font("Roboto", 0, 18));
            volver.setText("VOLVER");
            imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoSesion.jpg")));
        } else
        {
            // Configuraciones para el idioma japonés
            archivo.setText("アーカイブ");
            idiomas.setText("語");
            salida.setText("ディスコネクト");
            usuario.setText("ユーザ:");
            contra.setText("パスワ-ド:");
            volver.setFont(new java.awt.Font("Dialog", 0, 18));
            volver.setText("戻る");
            ingresar.setText("ログイン");
            ingresar.setFont(new java.awt.Font("Dialog", 0, 18));
            imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoSesionJP.jpg")));
        }
    }

    @Override
    public AudioClip obtenerSonido() {
        // Obtener el archivo de sonido
        AudioClip sonidoBoton;
        URL url = getClass().getResource("/sonidos/raton.wav");
        sonidoBoton = java.applet.Applet.newAudioClip(url);
        return sonidoBoton;
    }

    @Override
    public void reproducirSonidoBoton() {
        // Reproducir el sonido obtenido
        obtenerSonido().play();
    }

}
