/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazgrafica;

import herencias.Idiomas;
import interfacespropias.Sonidos;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author ShibaXpath
 */
public class SelectorIdioma extends Idiomas implements Sonidos {

    /**
     * Creates new form InicioApp
     */
    public SelectorIdioma() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Kizuna App");
        setResizable(false);
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/miicono.jpg"));

        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        idiomaJp = new javax.swing.JButton();
        idiomaEsp = new javax.swing.JButton();
        continuar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        fondoSelector = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fondoPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(459, 457));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(820, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(420, 490));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/kizuna.png"))); // NOI18N
        fondo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarnopulsado.png"))); // NOI18N
        fondo.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));
        botonCerrar.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseEntered(MouseEvent e) {
                // Cambiar icono al pasar el ratón
                botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png")));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                // Restaura icono al sacar ratón
                botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarnopulsado.png")));
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                // Cierra la aplicación al hacer clic en la etiqueta
                System.exit(0);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 580));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elige tu idioma/言語を選択する");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        idiomaJp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jp.png"))); // NOI18N
        idiomaJp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idiomaJpActionPerformed(evt);
            }
        });
        fondo.add(idiomaJp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 50, 40));

        idiomaEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/español.png"))); // NOI18N
        idiomaEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idiomaEspActionPerformed(evt);
            }
        });
        fondo.add(idiomaEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 50, 40));

        continuar.setBackground(new java.awt.Color(255, 255, 255));
        continuar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        continuar.setForeground(new java.awt.Color(255, 255, 255));
        continuar.setText("No seleccionable/選択不可");
        continuar.setEnabled(false);
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });
        fondo.add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 270, 70));

        salir.setBackground(new java.awt.Color(255, 255, 255));
        salir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("No seleccionable/選択不可");
        salir.setEnabled(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        fondo.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 270, 70));

        fondoSelector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mundial.png"))); // NOI18N
        fondo.add(fondoSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 590));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 480, 580));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoprincipal.jpg"))); // NOI18N
        jPanel1.add(fondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -5, 410, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idiomaJpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomaJpActionPerformed
        cambiarIdioma(false);
        reproducirSonidoBoton();
        super.setBandera(false);
    }//GEN-LAST:event_idiomaJpActionPerformed

    private void idiomaEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomaEspActionPerformed
        cambiarIdioma(true);
        reproducirSonidoBoton();
        super.setBandera(true);
    }//GEN-LAST:event_idiomaEspActionPerformed

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        InicioApp inicio = new InicioApp(); // Crea una instancia de la clase InicioApp
        reproducirSonidoBoton(); // Llama al método reproducirSonidoBoton() para reproducir un sonido de botón
        inicio.setBandera(true); // Establece la bandera de inicio como verdadera en la instancia de InicioApp
        inicio.cambiarIdioma(super.isBandera()); // Llama al método cambiarIdioma() en la instancia de InicioApp con el valor de la bandera actual
        this.dispose(); // Cierra la ventana actual
        inicio.setVisible(true); // Hace visible la ventana de InicioApp

    }//GEN-LAST:event_continuarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        reproducirSonidoBoton();
        JOptionPane.showMessageDialog(null, "Aplicación cerrada con exito/アプリケーションは正常に終了しました", "Mensaje/メッセージ", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonCerrar;
    private javax.swing.JButton continuar;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel fondoPrincipal;
    private javax.swing.JLabel fondoSelector;
    private javax.swing.JButton idiomaEsp;
    private javax.swing.JButton idiomaJp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton salir;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cambiarIdioma(boolean idioma) {
        if (idioma)
        {
            // Si el idioma es verdadero
            continuar.setText("CONTINUAR"); // Establece el texto del botón "continuar" en "CONTINUAR"
            salir.setText("SALIR DE LA APLICACIÓN"); // Establece el texto del botón "salir" en "SALIR DE LA APLICACIÓN"
            continuar.setFont(new java.awt.Font("Roboto", 0, 18)); // Establece la fuente del botón "continuar" con una fuente específica
            salir.setFont(new java.awt.Font("Roboto", 0, 18)); // Establece la fuente del botón "salir" con una fuente específica
            activarBotones(); // Llama al método "activarBotones" para activar los botones
        } else
        {
            // Si el idioma es falso
            continuar.setText("進む"); // Establece el texto del botón "continuar" en "進む"
            salir.setText("アプリケーションを終了する"); // Establece el texto del botón "salir" en "アプリケーションを終了する"
            continuar.setFont(new java.awt.Font("Dialog", 0, 18)); // Establece la fuente del botón "continuar" con una fuente específica
            salir.setFont(new java.awt.Font("Dialog", 0, 18)); // Establece la fuente del botón "salir" con una fuente específica
            activarBotones(); // Llama al método "activarBotones" para activar los botones
        }

    }

    public void activarBotones() {
        continuar.setEnabled(true); // Habilita el botón "continuar"
        salir.setEnabled(true); // Habilita el botón "salir"
        continuar.setBackground(new java.awt.Color(255, 0, 51)); // Establece el color de fondo del botón "continuar" a rojo (RGB: 255, 0, 51)
        salir.setBackground(new java.awt.Color(255, 0, 51)); // Establece el color de fondo del botón "salir" a rojo (RGB: 255, 0, 51)

    }

    @Override
    public AudioClip obtenerSonido() {
        // Método para obtener el sonido del botón
        AudioClip sonidoBoton; // Variable para almacenar el sonido del botón
        URL url = getClass().getResource("/sonidos/raton.wav"); // Obtiene la URL del archivo de sonido
        sonidoBoton = java.applet.Applet.newAudioClip(url); // Crea un nuevo AudioClip a partir de la URL del sonido
        return sonidoBoton; // Devuelve el AudioClip del sonido del botón
    }

    @Override
    public void reproducirSonidoBoton() {
        // Método para reproducir el sonido del botón
        obtenerSonido().play(); // Reproduce el sonido obtenido a través del método obtenerSonido()
    }

}
