/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazgrafica;

import aplicacion.BomberoVoluntario;
import interfacespropias.Sonidos;
import java.applet.AudioClip;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author ShibaXpath
 */
public final class VinculoBomberoVoluntario extends BomberoVoluntario implements Sonidos {


    /**
     * Creates new form InicioApp
     */
    public VinculoBomberoVoluntario() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Kizuna App");
        setResizable(false);
        setIconImage(getIconImage());
    }

    public void setCampoMensaje(String campoMensaje) {
        this.campoMensaje.setText(campoMensaje);
    }

    
    

    @Override
    public Image getIconImage() {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/miicono.jpg"));

        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        cerrar = new javax.swing.JButton();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoMensaje = new javax.swing.JTextArea();
        menuSesion = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        salida = new javax.swing.JMenuItem();
        idiomas = new javax.swing.JMenu();
        español = new javax.swing.JMenuItem();
        japones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(204, 204, 204));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setBackground(new java.awt.Color(255, 0, 51));
        cerrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("CERRAR");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        fondo.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 220, 60));
        fondo.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 770, 20));
        fondo.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 760, 20));

        titulo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("INFORMACIÓN ADICIONAL:");
        fondo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        campoMensaje.setEditable(false);
        campoMensaje.setBackground(new java.awt.Color(204, 204, 204));
        campoMensaje.setColumns(20);
        campoMensaje.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        campoMensaje.setForeground(new java.awt.Color(0, 0, 0));
        campoMensaje.setRows(5);
        campoMensaje.setText(null);
        campoMensaje.setFocusable(false);
        campoMensaje.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(campoMensaje);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 750, 350));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        archivo.setText("Archivo");

        salida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        salida.setText("Salir");
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        archivo.add(salida);

        menuSesion.add(archivo);

        idiomas.setText("Idiomas");

        español.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        español.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/espaicon.png"))); // NOI18N
        español.setText("Español");
        español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                españolActionPerformed(evt);
            }
        });
        idiomas.add(español);

        japones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_DOWN_MASK));
        japones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/japoicon.png"))); // NOI18N
        japones.setText("日本語");
        japones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japonesActionPerformed(evt);
            }
        });
        idiomas.add(japones);

        menuSesion.add(idiomas);

        setJMenuBar(menuSesion);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void japonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japonesActionPerformed
        cambiarIdioma(false);
        super.setBandera(false);
        switch(super.getSexo()){
            case "Hombre":
                super.setSexo("男");
                break;
            case "Mujer":
                super.setSexo("女性");
        }
        
        if(super.getRango().equals("Bombero Voluntario")){
            super.setRango("ボランティア消防団");
        }
        
        campoMensaje.setText(super.devolverDescripcion());
    }//GEN-LAST:event_japonesActionPerformed

    private void españolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_españolActionPerformed
        cambiarIdioma(true);
        super.setBandera(true);
        switch(super.getSexo()){
            case "男":
                super.setSexo("Hombre");
                break;
            case "女性":
                super.setSexo("Mujer");
        }
        
        if(super.getRango().equals("ボランティア消防団")){
            super.setRango("Bombero Voluntario");
        }
        
        campoMensaje.setText(super.devolverDescripcion());
    }//GEN-LAST:event_españolActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salidaActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.dispose();
        Plataforma p = new Plataforma();
        p.setBandera(super.isBandera());
        p.cambiarIdioma(super.isBandera());
        p.setNombreUsuario(super.getUsuario());
        p.setVisible(true);
    }//GEN-LAST:event_cerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivo;
    private javax.swing.JTextArea campoMensaje;
    private javax.swing.JButton cerrar;
    private javax.swing.JMenuItem español;
    private javax.swing.JPanel fondo;
    private javax.swing.JMenu idiomas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem japones;
    private javax.swing.JMenuBar menuSesion;
    private javax.swing.JMenuItem salida;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cambiarIdioma(boolean idioma) {

        if (idioma)
        {
            archivo.setText("Archivo");
            idiomas.setText("Idiomas");
            salida.setText("Desconectar");
            cerrar.setFont(new java.awt.Font("Roboto", 0, 18));
            cerrar.setText("CERRAR VENTANA");
            titulo.setFont(new java.awt.Font("Roboto", 0, 24));
            titulo.setText("INFORMACIÓN ADICIONAL:");
            
        } else
        {
            archivo.setText("アーカイブ");
            idiomas.setText("語");
            salida.setText("ディスコネクト");
            cerrar.setFont(new java.awt.Font("Dialog", 0, 18));
            cerrar.setText("ウィンドウを閉じる");
            titulo.setText("追加情報:");
            titulo.setFont(new java.awt.Font("Dialog", 0, 24));
        }
    }

    @Override
    public AudioClip obtenerSonido() {
        AudioClip sonidoBoton;
        URL url = getClass().getResource("/sonidos/raton.wav");
        sonidoBoton = java.applet.Applet.newAudioClip(url);
        return sonidoBoton;
    }

    @Override
    public void reproducirSonidoBoton() {
        obtenerSonido().play();
    }
}
